### ISSUE TITLE
Display models/textures/etc. from 3d software modeling tool?

### ISSUE THREAD

**Issue by molecule** [nordprojects/lantern#9]
I LOVE this project, and am planning to build out a more extensive version of this in the near future.

After reading the code I'm still unclear on this: is it possible to display materials/textures/models from Unity (or another 3d modeling software tool) via this display?

I'm basically still trying to wrap my head around how to "talk" to the projector, and how to tell it what to display...

Thanks so much for any pointers you can give! Thanks also for the incredible (and beautiful!) documentation of this awesome project!

**Comment by joerick** [comment]
Hi @molecule ! Thanks for the kind words! To display something different on Lantern your best bet is to create your own channel. Check out [the guide](https://github.com/nordprojects/lantern#making-your-own-channels) here to get started.

In terms of showing a 3d model, I'm not totally sure to be honest! Could you get away with prerendering that model to an image or a video? That might be the simplest path. Otherwise, you could try creating a [Processing](https://processing.org/) sketch and porting that over to a Lantern channel. That's how we made the [Space porthole](https://github.com/nordprojects/lantern/tree/master/things/src/main/java/com/example/androidthings/lantern/channels/spaceporthole) example.

I hope that helps!

**Comment by molecule** [comment]
Thanks! Yes I think I was unclear in my post: I'm just trying to display images or videos from the Lantern. but Unity is the only tool I know of to create models/textures. I think I'm just generally a little lost on how to display images through the projector...

THe porthole example is super helpful though, thanks!

**Comment by joerick** [comment]
There isn't a channel that just displays images, but if you're familiar with Kotlin or app development in general it shouldn't be too hard to create one. 

Simplest way would probably be to make a channel that creates one of these : https://developer.android.com/reference/android/widget/ImageView

Good luck!
